export const data = [
  {
    id: 1,
    name: "Nguyễn Văn A",
    dob: "28/02/1990",
    email: "nvana@gmail.com",
    address: "Ba Đình, Hà Nội",
    status: true,
    block: true,
  },
  {
    id: 2,
    name: "Trần Thị B",
    dob: "15/07/1985",
    email: "ttb@gmail.com",
    address: "Cầu Giấy, Hà Nội",
    status: false,
    block: true,
  },
  {
    id: 3,
    name: "Lê Văn C",
    dob: "03/10/2000",
    email: "lvc@gmail.com",
    address: "Hai Bà Trưng, Hà Nội",
    status: true,
    block: true,
  },
  {
    id: 4,
    name: "Phạm Thị D",
    dob: "20/05/1995",
    email: "ptd@gmail.com",
    address: "Hoàn Kiếm, Hà Nội",
    status: false,
    block: true,
  },
  {
    id: 5,
    name: "Ngô Văn E",
    dob: "12/11/1988",
    email: "nve@gmail.com",
    address: "Cầu Giấy, Hà Nội",
    status: true,
    block: true,
  },
  {
    id: 6,
    name: "Nguyễn Văn A",
    dob: "28/02/1990",
    email: "nvana@gmail.com",
    address: "Ba Đình, Hà Nội",
    status: true,
    block: true,
  },
  {
    id: 7,
    name: "Trần Thị B",
    dob: "15/07/1985",
    email: "ttb@gmail.com",
    address: "Cầu Giấy, Hà Nội",
    status: false,
    block: true,
  },
  {
    id: 8,
    name: "Lê Văn C",
    dob: "03/10/2000",
    email: "lvc@gmail.com",
    address: "Hai Bà Trưng, Hà Nội",
    status: true,
    block: true,
  },
  {
    id: 9,
    name: "Phạm Thị D",
    dob: "20/05/1995",
    email: "ptd@gmail.com",
    address: "Hoàn Kiếm, Hà Nội",
    status: false,
    block: true,
  },
  {
    id: 10,
    name: "Ngô Văn E",
    dob: "12/11/1988",
    email: "nve@gmail.com",
    address: "Cầu Giấy, Hà Nội",
    status: true,
    block: true,
  },
];
